//list.js
export const ADD_ITEM='ADD_ITEM'
export const DELETE_ITEM='DELETE_ITEM'
export const ACTIVE_ITEM='ACTIVE_ITEM'
// export const TOGGLE_SELETED_STATUS='TOGGLE_SELETED_STATUS'
export const INIT_DATA='INIT_DATA'
export const SELECT_ITEM='SELECT_ITEM'
export const DESELECT_ITEM='DESELECT_ITEM'
export const TOGGLE_CHOOSE_ITEM='TOGGLE_CHOOSE_ITEM'
export const TOGGLE_ITEM_STATUS='TOGGLE_ITEM_STATUS'
export const TOGGLE_ALL_STATUS='TOGGLE_ALL_STATUS'


//user.js
